name: Purge jsDelivr CDN cache

on:
  push:
    branches:
      - main
    paths:
      - 'external.js'
      - 'external.css'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr CDN cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/smartnm/eroum@main/external.js"
          curl -X GET "https://purge.jsdelivr.net/gh/smartnm/eroum@main/external.css"
