name: Purge jsDelivr CDN cache

on:
  push:
    branches:
      - main
    paths:
      - 'eroum.js'
      - 'eroum.css'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr CDN
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/smartnm/eroum@main/eroum.js"
          curl -X GET "https://purge.jsdelivr.net/gh/smartnm/eroum@main/eroum.css"
